//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketingDepartment
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsignmentsProduct
    {
        public int ConsignmentProductId { get; set; }
        public int ConsignmentId { get; set; }
        public int ProductId { get; set; }
        public int ProductsCount { get; set; }
    
        public virtual Consignment Consignment { get; set; }
        public virtual Product Product { get; set; }
    }
}
