//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketingDepartment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consignment()
        {
            this.ConsignmentsProducts = new HashSet<ConsignmentsProduct>();
        }
    
        public int ConsignmentId { get; set; }
        public int CustomerId { get; set; }
        public int BankId { get; set; }
        public string Destination { get; set; }
        public System.DateTime Date { get; set; }
        public double Price { get; set; }
    
        public virtual Bank Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsignmentsProduct> ConsignmentsProducts { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
