//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketingDepartment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarketingDepartmentDatabaseEntities1 : DbContext
    {
        public MarketingDepartmentDatabaseEntities1()
            : base("name=MarketingDepartmentDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Consignment> Consignments { get; set; }
        public virtual DbSet<ConsignmentsProduct> ConsignmentsProducts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<PriceHistory> PriceHistories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    }
}
