//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketingDepartment
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceHistory
    {
        public int PriceHistoryId { get; set; }
        public System.DateTime Date { get; set; }
        public float Price { get; set; }
        public int ProductId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
